version: "2"

services:
  web:
    build: ./web/
    restart: always
    ports:
      - "9081:8000"
    volumes:
      - ./web:/app
    command: python manage.py runserver 0.0.0.0:8000
   # command: django-admin startproject app .
